language: node_js
node_js:
- 13.2
deploy:
  provider: s3
  cleanup: true
  skip_cleanup: true
  access_key_id: AKIAZIUCQ6FCCBH6336J
  secret_access_key:
    secure: QS9lJVbreHuArLBOOXcg66MulKmzDj7pEYoV6c4vMTZzXsfTppCaiHe1c2bjwJT4bKWqTjn4O7jFwLZMGZJ+EuSG5TS5vjBbF7vTV0g+8H5rE4Z+XSGJL/KkBbl23XIhgvRZkSw2/Y2xoYAupwkJ3n/eSpFFpH0h1mv5gVq7HzrcVFUe5Rcb5iMff8NqzJ9uijZILSzN8HB3wasdr6Yj2keyJTym4HYMEkLeqCyMIKn1LXgiwZGODiIdZQfO3jNT4mKuhqQ2+L+nKWUcuYwXDlTgrdmEZJwzw3yKmnx8NPV3h8fhvwxLrPj02HbrSp3X6nH2gOw8ukzRc+DJHUKjMgEyIW6r0MorJtWOZ/rzOCQDnZV/HbbHCIpBJ+iOT8GHijVSkHOP7phgARKvONo3mtP2H/hZe62OXrDgqcDKY+Z1JBMSvVZ9DRhgAHNesLdFwcFmUqH7kD5cU+HXkSlACRAyxRkGlQXp8GRBn4CNVqwp/8RsNxAxg+troZsJw6E6j5u6tWDT/NKRvnNztTlAKUpHzuMF1XOoBkFOXXLZb2hyJunQrb6PUbFMBqGXYVdyVCFxhGUO6Ci3/OK9J1jk+PLIPMqDDBZRYjjaMD85gu2P1mXKsqIeqClLz/oAz8MWZWs7LT43nlasV4VHhld0igKhMTOaVwP7vbyr4cUy9xc=
  bucket: alpheios-grammars
  region: us-east-2
  local_dir: "."
  upload_dir: smyth
  acl: public_read
  cache_control: max-age=604800
  on:
    repo: alpheios-project/grammar-smyth
    branch: production
